#define SS_PRIORITY_TRADE 10  // Adds/removes merchants.

#define MERCHANT_INCLUDE_THIS_TYPE		BITFLAG(0)
#define MERCHANT_INCLUDE_SUBTYPES		BITFLAG(1)
#define MERCHANT_INCLUDE_ALL			(MERCHANT_INCLUDE_THIS_TYPE|MERCHANT_INCLUDE_SUBTYPES)
#define MERCHANT_EXCLUDE_THIS_TYPE		BITFLAG(2)
#define MERCHANT_EXCLUDE_SUBTYPES		BITFLAG(3)
#define MERCHANT_EXCLUDE_ALL			(MERCHANT_EXCLUDE_THIS_TYPE|MERCHANT_EXCLUDE_SUBTYPES)
